var acto1 = [
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Se encuentran otra tarde vagando por las calles, sin ningún lugar al que apuntar.\n En un pueblo alejado de todo no hay mucho para hacer. Los negocios cierran temprano, la plaza está vacía y siempre parece que el viento arrastra más tierra que gente.",
  },

  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Nan camina pateando piedritas por la vereda mientras Laura mira las casas abandonadas del barrio.",
    sonido: "piedritas"
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Ventanas rotas. Jardines secos.\nLugares donde ya no pasa nada.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "No había un peso. Nunca podrían pagar un espacio así.\nLo más cerca que podían estar de tener algo propio era colarse en lugares vacíos buscando un poco de emoción.",
    sonido: "perro"
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Laura se detiene frente a una medianera baja y le hace señas a Nan.",
    
  },
  {
    fondo: "patio",
    Laura: true,
    Nan: false,
    Moli: false,
    hablante: "Laura",
    texto: "-Dale, mandate.",
  },
  {
    fondo: "patio",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "narrador",
    texto: "Nan apoya el pie sobre las manos de Laura y trepa como puede.",
  },
  {
    fondo: "patio",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "-Si hay un perro acá adentro te mato.",
  },
  {
    fondo: "patio",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Laura",
    texto: "-Callate y subí.",
  },
  {
    fondo: "patio",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "narrador",
    texto:
      "Nan cae del otro lado entre pastos altos y tierra húmeda. Empuja una puerta para abrirle a Laura.",
  },
  {
    fondo: "interior1",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Adentro huele a polvo viejo y madera mojada. Paredes descascaradas. \nNan camina despacio mirando alrededor.\nEl lugar está destruido, pero no muerto.",
  },
  {
    fondo: "interior1",
    Laura: false,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "-Boluda, imaginá esto lleno de gente.",
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "narrador",
    texto: "Laura se ríe apenas.",
    sonido: "risas2"
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Laura",
    texto: "-Lleno de qué gente?",
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto:
      "-No sé… gente. Bandas, amigos, desconocidos. Que pasen cosas.\nTipo… un lugar donde no tengas que consumir algo para quedarte. Donde puedas venir aunque no tengas un mango.",
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Laura",
    texto: "-Un lugar para hacer fechas.",
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "-y fiestas",
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Laura",
    texto: "-Y talleres capaz.",
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "-Y quedarse hasta cualquier hora.",
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Laura",
    texto: "-Nos van a odiar los vecinos.",
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "-Entonces significa que estaría bueno",
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "narrador",
    texto: "...",
    fadeOut: true,
  },
  {
    fondo: "interior1",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Tomó unos días sacar la basura de las habitaciones e improvisar un escenario con las cosas viejas que tenían guardadas en el galpón de Laura. \nNan decoró con luces olvidadas de alguna Navidad pasada.",
  },
  {
    fondo: "interior1",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "El lugar estuvo vacío durante demasiados años. \nAsí que la atención vecinal llegó rápido, incluso antes de que hubiera música.",
  },
  {
    fondo: "calle2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Antes del anochecer ven a Nan acercarse a la casa con un par de birras bajo el brazo. \nUn vecino la intercepta apenas cruza el portón. \nTendrá unos cincuenta largos. Mala predisposición automática.",
    sonido: "piedritas",
  },
  {
    fondo: "calle2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "vecino",
    texto: "-Ustedes viven acá?",
  },
  {
    fondo: "calle2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "Nan",
    texto: "-No como tal.",
  },
  {
    fondo: "calle2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "vecino",
    texto: "-Fíjense. No pueden hacer lo que quieran acá.",
    sonido: "perro",
  },
  {
    fondo: "calle2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "Nan",
    texto: "-Sí, sí, quédese tranquilo nomás, señor.",
  },
  {
    fondo: "calle2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Nan ni siquiera lo mira cuando entra. El hombre se queda murmurando mientras se aleja.",
  },
  {
    fondo: "calle2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "vecino",
    texto: "-Pendejas maleducadas...",
  },
  {
    fondo: "interior1",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Nan deja una lata al lado de Laura, que está agachada armando un alargue para conectar el equipo.",
    sonido: "lata"
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: false,
    Moli: false,
    hablante: "Laura",
    texto: "-Está caliente.",
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "-Es lo que había.",
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "narrador",
    texto: "Se deja caer contra la pared.",
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "-Igual eso es lo de menos. Ya vino un vecino a joder.",
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Laura",
    texto: "-Pero si todavía no hicimos nada.",
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "-Exacto.",
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Laura",
    texto: "-Viejo choto...",
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Nan",
   sonido: "risas",
  },
  {
    fondo: "interior1",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Laura",
    texto: "-No le des bola. Con una queja no puede hacer nada.",
  },
  {
    fondo: "interior1",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Laura vuelve a conectar cables.\nEl lugar ya empezó a existir para otros y eso también significa problemas.",
  },
  {
    fondo: "interior1",
    Laura: false,
    Nan: false,
    Moli: false,
    sasha: false,
    decision: true,
    opciones: [
      {
        texto: "Hacer la fecha igual",
        valor: { decision1: 1 },
      },
      {
        texto: "Esperar",
        valor: { decision1: 0 },
      },
    ],
    fadeOut: true,
  }];
var Acto1A = [
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    sasha: false,
    hablante: "narrador",
    texto:
      "El espacio estaba apenas listo, la iluminación era poca, los equipos eran viejos y los cables cruzaban habitaciones enteras.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    sasha: false,
    hablante: "narrador",
    texto: "Pero todo funcionaba.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    sasha: false,
    hablante: "narrador",
    texto:"Ya habían corrido la voz de que ese fin de semana iba a haber una fecha.",
    },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    sasha: false,
    hablante: "narrador",
    texto: "Tocaban amigos, conocidos y bandas improvisadas a último momento.",
    sonido: "fecha"
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    sasha: false,
    hablante: "narrador",
    texto: " La gente empezó a llegar antes de que terminara de caer el sol.Después el patio entero lleno de humo, cerveza y ruido.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    sasha: false,
    hablante: "narrador",
    texto:
      "A las cuatro de la mañana quedan pocas personas ayudando a limpiar. Todos están agotados pero felices. \n Nan mira sonriendo el desastre alrededor.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    sasha: false,
    hablante: "narrador",
    texto:
      "En ese momento una chica se acerca tambaleando apenas, todavía con una botella en la mano.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: true,
    sasha: false,
    hablante: "Moli",
    texto: "-Che… estuvo re bueno esto.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: true,
    Moli: true,
    sasha: false,
    hablante: "Nan",
    texto: "-Sí?",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: true,
    Moli: true,
    sasha: false,
    hablante: "Moli",
    texto: "-Hace años no pasa nada por acá.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: true,
    Moli: true,
    sasha: false,
    hablante: "Moli",
    texto:
      "-Todos terminan yéndose a capital o encerrándose en su casa.\n Necesitábamos un lugar así. Acá parece que si querés hacer cualquier cosa tenés que inventarla vos.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: true,
    sasha: false,
    hablante: "narrador",
    texto: "Laura la observa con cierta desconfianza.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: true,
    sasha: false,
    hablante: "Laura",
    texto: "-Allá te miran como si vinieras de otro planeta.",
  },
   {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: true,
    sasha: false,
    hablante: "Moli",
    texto: "—Porque venimos de otro planeta.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: true,
    sasha: false,
    hablante: "Laura",
    texto: "-Todavía ni sabemos qué es “esto”.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: true,
    sasha: false,
    hablante: "Moli",
    texto: "—No sé. Algo nuestro.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: true,
    sasha: false,
    hablante: "Moli",
    texto:
      "-Las calles son del pueblo.\n Si un lugar está vacío y ustedes lo llenan de gente, entonces ya es más útil que antes.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: true,
    sasha: false,
    hablante: "Moli",
    texto:
      "-Fechas, ferias, movidas políticas, lo que pinte. Pero si esto sigue, quiero estar.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    sasha: false,
    hablante: "narrador",
    texto:
      "Más tarde mientras bajan las últimas cosas, Laura encuentra un papel pegado afuera del portón.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    sasha: false,
    hablante: "narrador",
    texto:
      "Es una denuncia por ruidos molestos.",
    fadeOut: true,
  },
];
var Acto1B = [
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    sasha: false,
    hablante: "narrador",
    texto:
      "Deciden esperar unas semanas más antes de hacer una fecha grande.\n Hablan con vecinos, arreglan habitaciones, intentan que el lugar parezca menos improvisado y más habitable.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: true,
    Moli: false,
    sasha: false,
    hablante: "Nan",
    texto: "Parece que estamos armando un jardín de infantes.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: false,
    sasha: false,
    hablante: "Laura",
    texto: "Prefiero eso antes que nos clausuren en la primera semana.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    sasha: false,
    hablante: "narrador",
    texto: "El riesgo legal baja un poco pero también baja el entusiasmo.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    sasha: false,
    hablante: "narrador",
    texto:
      "Finalmente hacen una noche pequeña. Tocan bandas tranquilas y hay birra barata, todo sale bien. Ni caos ni policìas",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    sasha: false,
    hablante: "narrador",
    texto:
      "pero tampoco da la sensación de que algo importante estuviera pasando.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    sasha: false,
    hablante: "narrador",
    texto: "La noche termina temprano",
    fadeOut: true,
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    sasha: false,
    hablante: "narrador",
    texto:
      "Más tarde encuentran a una chica sentada en una de las ventanas, fumando mientras mira el patio vacío.\n Se queda observando las luces navideñas colgadas entre las paredes descascaradas.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: true,
    sasha: false,
    hablante: "Moli",
    texto: "-Está lindo esto.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: true,
    Moli: true,
    sasha: false,
    hablante: "Nan",
    texto: "-“Lindo” no era exactamente la idea.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: true,
    Moli: true,
    sasha: false,
    hablante: "Moli",
    texto: "-Entonces no aflojen tanto.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: true,
    sasha: false,
    hablante: "Laura",
    texto: "-Qué más podemos hacer? Nos van a echar en una semana sino.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: true,
    sasha: false,
    hablante: "Moli",
    texto:
      "-Sí… pero si se preocupan demasiado por eso, terminan siendo un bar cualquiera.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: true,
    sasha: false,
    hablante: "Moli",
    texto:
      "-Nadie vino porque necesitaba estar acá.",
  },
   {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: true,
    sasha: false,
    hablante: "Nan",
    texto:
      "-Como?",
  },
   {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: true,
    sasha: false,
    hablante: "Moli",
    texto:
      "-Todos se fueron apenas terminó la música. Los lugares importantes son los que la gente no quiere abandonar.",
    fadeOut: true,
    
  },
];

var acto2 = [
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "El lugar empieza a tener olor propio, ya no parece una casa abandonada.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Moli pasó gran parte de la tarde terminando un mural enorme en una de las paredes del patio. A su alrededor, la vida del lugar seguía moviéndose sin prestar demasiada atención.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      " Algunos fumaban sentados en el piso, apoyados contra las columnas, mientras una línea de bajo repetida una y otra vez resonaba desde el fondo, alguien ensayaba contra una pared descascarada.",
     sonido: "dalejano",
    
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Cerca de la entrada, dos chicas trabajaban sobre unos carteles para una feria próxima, rodeadas de pinceles, pintura y papeles manchados.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Desde la cocina llegaban risas, estaba llena de personas que nadie parecía conocer demasiado bien, tomando mate y ocupando el espacio con la naturalidad de quienes llevan años viviendo ahí, aunque muchos hubieran llegado apenas unas semanas antes.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "—Che, una banda de La Plata quiere tocar acá.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Laura",
    texto: "—Quiénes?",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "—No sé. Pero llenaron todos los lugares donde tocaron.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Laura",
    texto: "—Y cuánto quieren cobrar?",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "—Dormir acá y birra.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Laura",
    texto: "—Perfecto",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Con cada fecha aparece más gente. Caras nuevas, amigos de amigos. Una noche el patio se llena hasta no dejar espacio para nadie más.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      " La luz se corta dos veces. Unos vomitan en el baño. Un amplificador empieza a fallar y por un momento parece que todo se va a ir al carajo.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "pero el recital termina siendo uno de los mejores que hicieron.",
     sonido: "canto",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      " La gente canta canciones que ni siquiera conoce.\n Cuando vuelven los apagones, algunos improvisan las luces con linternas y celulares.\n Los vecinos golpean las paredes durante horas, pero nadie les presta atención.",
   
    fadeOut: true,
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "El cielo ya está aclarando y el sol empieza a asomarse entre los casas y los árboles.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Laura revisa cuentas en una libreta ",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: false,
    Moli: false,
    hablante: "Laura",
    texto: "—Ni plata hicimos otra vez.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Nan sigue tirada en un sillón roto.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "—Pero vino muchísima gente.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Laura",
    texto: "—La gente no paga los cables rotos",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Al día siguiente golpean el portón. Un hombre entra con una carpeta bajo el brazo. No parece agresivo.",
    sonido: "golpe"
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "Inspector",
    texto: "—Buenas. Vine por una denuncia.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Nadie responde.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "Inspector",
    texto: "—Quién está a cargo acá?",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Laura y Nan se miran.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Ninguna responde primero.",
    fadeOut: true,
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "La semana siguiente trabajan más que nunca.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Moli apareció una tarde con un grupo de personas y varios metros de tela bajo el brazo. Durante días ocuparon una esquina del patio, pintando una bandera enorme destinada a colgar detrás del escenario.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Nan, en cambio, casi siempre estaba afuera. Pasaba horas recorriendo calles, pegando flyers en postes, paredes y negocios.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Laura se movía de otra manera. Hablaba con comerciantes, hacía preguntas y buscaba soluciones donde nadie más las veía. Gracias a ella, una verdulería del barrio empezó a guardar cajones de madera que terminaron convertidos en bancos improvisados para el patio.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "De a poco, el espacio empezó a llenarse de cosas construidas entre todos. Ninguna parecía importante por sí sola, pero juntas hacían que el lugar se sintiera cada vez más vivo.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "A medida que se acerca el fin de semana, el lugar empieza a transformarse otra vez.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Llegan emprendedores con percheros llenos de ropa usada para la feria. Otros cargan proyectores, parlantes o cajas con cables enredados porque abrirán la noche con cortos independientes. Después estarán los recitales de punk y noise.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Más tarde, para los que se queden manija, se quedarán con el dj hasta las 3 o 4. En el patio, entre grupos que conversan y fuman, alguien terminará improvisando poesía para quien quiera escuchar.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Todo parece improvisado, caótico, a punto de desarmarse.\n Y, sin embargo, de alguna manera siempre funciona. Apenas de milagro.",
  },
  
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    decision: true,
    opciones: [
      {
        texto: "Mantener las fechas\n a la gorra",
        valor: { decision2: 1 },
      },
      {
        texto: "Cobrar entrada",
        valor: { decision2: 0 },
      },
    ],
  },
];
var acto2A = [
  {
    fondo: "interior2",
    Laura: false,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto:
      "—Si empezamos a poner precio a todo terminamos siendo otro bar más.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Laura",
    texto: "—Y si no lo hacemos terminaremos cerrando.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "—Bueno. Entonces veremos cuánto dura.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "narrador",
    texto:
      "La gente llega, se queda un tiempo y deja algo de sí antes de seguir su camino.\n Cada fin de semana transforma el espacio en algo distinto.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "narrador",
    texto:
      "Los horarios se mezclan, las habitaciones se llenan de voces y siempre hay alguien entrando o saliendo por alguna puerta. El caos se vuelve parte de la rutina.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "La plata desaparece más rápido de lo que entra. Mientras el lugar se llena de personas, proyectos y actividades, el trabajo detrás de escena también se multiplica.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Una madrugada cuando la joda ya había terminado, una chica desconocida mira alrededor fascinada.",
      sonido: "fecha2",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "Sasha",
    texto: "—No sabía que todavía existían lugares así.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "Nan",
    texto: "—Nosotras tampoco.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Miran las luces navideñas colgadas sobre el patio.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "Sasha",
    texto: "—Parece que en cualquier momento todo se puede prender fuego.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "Nan",
    texto: "—Esa es la propuesta estética.",
    sonido: "risas",
    fadeOut: true,
  },
  
];
var acto2B = [
  {
    fondo: "interior2",
    Laura: true,
    Nan: false,
    Moli: false,
    hablante: "Laura",
    texto: "—No podemos seguir así.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "—La gente ya pone plata en la barra.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Laura",
    texto: "—No alcanza.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: true,
    hablante: "Moli",
    texto: "—Si cobramos mucho cambia la gente que viene.",
  },
  {
    fondo: "interior2",
    Laura: true,
    Nan: true,
    Moli: true,
    hablante: "Laura",
    texto: "—Y si no cobramos nada, un día no vamos a abrir más.",
     fadeOut: true,
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "De a poco, las luces iluminan como deberían y ya no quedan rincones enteros hundidos en la penumbra. En la puerta aparecen horarios escritos, los cables dejan de serpentear por el piso y los problemas técnicos dejan de interrumpir cada actividad.",
  },
  {
    fondo: "interior2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Todo funciona mejor, con más orden y menos sobresaltos",
    fadeOut: true,
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Dos chicos llegan para una fecha.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Miran el precio escrito con fibrón en la entrada.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "chico",
    texto: "—qué pasó? Ahora hay que pagar solo para estar?",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "Nan",
    texto: "—Sigue siendo barato.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "chico",
    texto: "—Sí… pero antes parecía de todos.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Los dos se van.",
    fadeOut: true,
  },
];

var acto3 = [
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Los meses pasan casi sin que nadie los cuente.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "El lugar se transforma en algo más difícil de definir, una especie de ciudad diminuta escondida detrás de un portón oxidado.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Si no hay una banda ensayando en alguna habitación, hay un taller ocupando el patio.\n Si el taller termina, aparecen mates sobre una mesa improvisada y la conversación sigue hasta entrada la noche. Las puertas se abren y se cierran constantemente, pero nunca llegan a estar realmente cerradas.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Una tarde, Laura entra a la cocina buscando agua.",
  },
  {
    fondo: "interior3",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Encuentra a tres desconocidos preparando café como si estuvieran en su propia casa.",
  },
  {
    fondo: "interior3",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "Laura",
    texto: "—Ustedes quiénes son?",
  },
  {
    fondo: "interior3",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "chico",
    texto: "—Amigos de Sasha.",
  },
  {
    fondo: "interior3",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "Laura",
    texto: "—Y Sasha?",
  },
  {
    fondo: "interior3",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "chico",
    texto: "—No sabemos..",
  },
  {
    fondo: "interior3",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "Laura",
    texto: "—Bueno. Traten de no prender fuego nada.",
  },
  {
    fondo: "interior3",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "A veces Laura tiene la sensación de que el lugar funciona solo. Que ellas apenas lo acompañan, como una máquina que ya aprendió a moverse sin quien la encendió.",
  },
  {
    fondo: "interior3",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Las fechas son cada vez más grandes, también el desastre que dejan atrás. Una vez desaparecieron dos micrófonos.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Una mujer aparece durante una de las ferias de domingo.",
  sonido: "tacones",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "No parece perdida, pero tampoco parece parte del lugar. Camina despacio entre los puestos con una carpeta apretada bajo el brazo.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Más tarde encuentra a Laura.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Hablan durante más de una hora sentadas. La mujer trabaja para un programa cultural del municipio, le explica que vienen siguiendo el crecimiento del espacio desde hace tiempo. Habla de redes culturales, proyectos independientes y fortalecimiento comunitario.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Menciona subsidios, equipos de sonido, arreglos para el edificio, difusión, asistencia técnica.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "Laura",
    texto: "—Y qué quieren a cambio?",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "Mujer",
    texto: "—Simplemente que funcione dentro de ciertas reglas.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Laura recibe los papeles.\n Horarios.\n Responsables.\n Protocolos.\n Rendiciones.\n Firmas.\n Más papeles.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "La mujer se retira para que puedan discutirlo en privado",
    fadeOut: true,
  },
  {
    fondo: "interior3",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Nan señala la carpeta.",
  },
  {
    fondo: "interior3",
    Laura: false,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "—Y después qué?",
  },
  {
    fondo: "interior3",
    Laura: true,
    Nan: true,
    Moli: true,
    hablante: "Laura",
    texto: "—Después qué de qué?",
  },
  {
    fondo: "interior3",
    Laura: true,
    Nan: true,
    Moli: true,
    hablante: "Nan",
    texto: "—Después de aceptar.",
  },
  {
    fondo: "interior3",
    Laura: true,
    Nan: true,
    Moli: true,
    hablante: "narrador",
    texto: "Laura se encoge de hombros.",
  },
  {
    fondo: "interior3",
    Laura: true,
    Nan: true,
    Moli: true,
    hablante: "Laura",
    texto: "—Después seguimos haciendo lo mismo que hacemos ahora.",
  },
  {
    fondo: "interior3",
    Laura: true,
    Nan: true,
    Moli: true,
    hablante: "narrador",
    texto: "Moli niega con la cabeza.",
  },
  {
    fondo: "interior3",
    Laura: true,
    Nan: true,
    Moli: true,
    hablante: "Moli",
    texto: "—Nunca es así.",
  },
  {
    fondo: "interior3",
    Laura: false,
    Nan: false,
    Moli: false,
    decision: true,
    opciones: [
      {
        texto: "RECHAZAR EL PROGRAMA\n MUNICIPAL",
        valor: { decision3: 1 },
      },
      {
        texto: "ACEPTAR EL PROGRAMA\n MUNICIPAL",
        valor: { decision3: 0 },
      },
    ],
  },
];
var acto3A = [
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Después de varias discusiones, de darle vueltas al asunto y de imaginar escenarios posibles, terminan rechazando la propuesta.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "La mujer vuelve unos días después para recibir la respuesta.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Al principio nada cambia , los problemas siguen exactamente donde estaban.\n Por momentos incluso parece que tomaron una decisión absurda",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "—Y si nos equivocamos?",
  },
  {
    fondo: "patio2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Laura",
    texto: "—Puede ser.",
  },
  {
    fondo: "patio2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "—Nada más?",
  },
  {
    fondo: "patio2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Laura",
    texto: "—Qué querés que te diga?",
  },
  {
    fondo: "patio2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Nan",
    texto: "—Que valió la pena.",
  },
  {
    fondo: "patio2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "narrador",
    texto: "...",
  },
  {
    fondo: "patio2",
    Laura: true,
    Nan: true,
    Moli: false,
    hablante: "Laura",
    texto: "—Todavía no lo sé.",
  },

  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "La noticia se esparce y empiezan a llegar mensajes de ayuda. Colectivo de artistas y bandas colaboran a mantener el espacio.",
    fadeOut: true,
  },
];
var acto3B = [
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "La discusión dura varios días. La carpeta aparece sobre mesas distintas, debajo de flyers, entre botellas vacías y listas de bandas. Nadie parece convencido.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Pero al final aceptan.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Al principio los cambios son pequeños. Empiezan a llegar cosas que antes parecían imposibles. Equipos que funcionan. Luces nuevas. Materiales para arreglar sectores de la casa que llevaban años deteriorándose. Por primera vez no tienen que esperar a que algo se rompa para recién pensar cómo repararlo.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Las fechas crecen y también crece la visibilidad del lugar.\n Durante años habían existido casi por accidente. Ahora parecían formar parte de algo oficial.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "No sabe si eso le gusta o no.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Cada vez menos personas sienten que ese lugar también les pertenece.",
    fadeOut: true,
  },
];

var final1 = [
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "El cierre no llegó como una tragedia.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Nadie irrumpió para expulsarlos ni hubo una última batalla contra funcionarios. Después de años sobreviviendo a denuncias, problemas económicos y discusiones interminables, el final resultó mucho más simple y mucho más difícil de combatir.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Llegó un momento en que seguir sosteniendo el lugar dejó de ser posible.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "La noticia comenzó a correr de boca en boca.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Aparecieron personas que nadie veía hacía muchísimo tiempo. Había música en el escenario principal, pero también en habitaciones improvisadas, en el patio y hasta en el pasillo de entrada.",
    sonido: "fecha3"
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Había personas y pintando, personas discutiendo política.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Las personas que se habían conocido allí comenzaron a organizar actividades en otros lugares.",
   
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Las bandas siguieron tocando, las ferias reaparecieron en plazas y galpones, los talleres se mudaron a casas particulares.",
    sonido: "fecha4"
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Nuevos espacios culturales empezaron a surgir por el conurbano.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Y aunque el portón permaneciera cerrado para siempre, la idea que había nacido detrás de él seguía apareciendo una y otra vez.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      " En nuevas personas.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "En nuevos espacios",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "En nuevas luchas.",

  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "...",
   fadeOut: true,
  },
];
var final2 = [
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "El centro cultural no cerró.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Durante un tiempo pareció que tampoco iba a cambiar demasiado. Los primeros acuerdos llegaron envueltos en promesas razonables.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Nada que pareciera amenazar realmente la identidad del lugar. Después de años sobreviviendo al borde del colapso, aceptar cierta ayuda parecía una decisión lógica. Incluso necesaria.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto: "Al principio nadie notó las diferencias",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "No aparecieron como prohibiciones directas. Nadie les entregó una lista de cosas que ya no podían hacer.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Algunas actividades dejaron de organizarse porque generaban demasiadas discusiones.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Ciertos eventos políticos empezaron a resultar incómodos, algunas bandas dejaron de ser convocadas.",
  },
  {
    fondo: "calle",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Una noche Moli encontró un afiche viejo guardado detrás de unos tablones.",
  },
  {
    fondo: "calle",
    Laura: true,
    Nan: true,
    Moli: true,
    hablante: "Moli",
    texto: "—Se acuerdan de esta noche?",
  },
  {
    fondo: "calle",
    Laura: true,
    Nan: true,
    Moli: true,
    hablante: "Nan",
    texto: "—la policía cayó dos veces",
  },
  {
    fondo: "calle",
    Laura: true,
    Nan: true,
    Moli: true,
    hablante: "Laura",
    texto: "—Y alguien prendió fuego un tacho de basura.",
  },
  {
    fondo: "calle",
    Laura: true,
    Nan:  true,
    Moli: true,
    hablante: "Nan",
    texto: "—Fue decorativo.",
  },
  {
    fondo: "calle",
    Laura: true,
    Nan: true,
    Moli: true,
    hablante: "narrador",
    texto: "Las chicas ríen.",
    sonido: "risas"
  },
  {
    fondo: "calle",
    Laura: true,
    Nan: true,
    Moli: true,
    hablante: "Nan",
    texto: "—Hoy no podriamos hacer algo así.",
  },
  {
    fondo: "calle",
    Laura: true,
    Nan: true,
    Moli: true,
    hablante: "narrador",
    texto: "...",
  },
  {
    fondo: "interior3",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "La gente ya no se quedaba hasta el amanecer.\n Ya no había discusiones eternas sobre cómo cambiar el mundo..",
  },
  {
    fondo: "interior3",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "El lugar seguía produciendo cultura pero de una forma mucho más predecible. Mucho más cómoda",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Alrededor de ellas el centro cultural seguía vivo. Lleno de gente. Lleno de actividad. Lleno de futuro.",
  },
  {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "Y sin embargo sabían que algo había quedado atrás durante el camino.",
  },
   {
    fondo: "patio2",
    Laura: false,
    Nan: false,
    Moli: false,
    hablante: "narrador",
    texto:
      "...",
    fadeOut: true,
  },
];